Generate and export information about the release

diff --git a/scripts/archive b/scripts/archive
--- a/scripts/archive
+++ b/scripts/archive
@@ -2,22 +2,53 @@
 
 set -euo pipefail
 
+help() {
+	cat <<-EOF >&2
+		Usage: $0 [-h] <tag>
+	EOF
+}
+
+options=$(getopt -n "$0" -o h -l help -- "$@")
+
+if test $? -ne 0; then
+	exit 1
+fi
+
+eval set -- "$options"
+
+while :; do
+	case "$1" in
+		-h|--help)
+			help
+			exit
+			;;
+		--)
+			shift
+			break
+			;;
+	esac
+done
+
 if test -z "$*"; then
-    echo "Missing argument, e.g. $0 classic/Fastbind/1.0.0" >&2
-    exit 1
+	echo "$0: missing argument, try --help for more information" >&2
+	exit 1
 fi
 
 if ! git rev-parse "$1" >/dev/null 2>&1; then
-    echo "$1 is not an existing tag" >&2
+    echo "$0: '$1' is not a valid tag" >&2
     exit 1
 fi
 
 platform="$(echo "$1" | cut -f1 -d/)"
 name="$(echo "$1" | cut -f2 -d/)"
 version="$(echo "$1" | cut -f3 -d/)"
-archive="$name-$version-$platform.zip"
+file="$name-$version-$platform"
 
 export RELEASE="$name $version ($platform)"
+export ARCHIVE="$file.zip"
+export CHANGELOG="$file.md"
 
 mkdir -p dist
-git archive --format=zip -o "dist/$archive" --prefix="$name/" "$1:$platform/$name/"
+
+git archive --format=zip -o "$ARCHIVE" --prefix="$name/" "$1:$platform/$name/"
+scripts/changelog "$1" > "$CHANGELOG"
