wip: Refactor scripts

diff --git a/scripts/archive b/scripts/archive
--- a/scripts/archive
+++ b/scripts/archive
@@ -1,49 +1,78 @@
 #!/usr/bin/env bash
 
-#
-# Generate add-on archive for given release tag.
-#
-
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $0 [-h] <tag>
+		About
+		        Generate add-on archive for given release tag.
+
+		Usage
+		        $script -h
+		        $script [-x] <tag>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
 	EOF
 }
 
-opts=$(getopt -n "$0" -o h -l help -- "$@")
-
-if test $? -ne 0; then
-	exit 1
-fi
-
-eval set -- "$opts"
-
-while :; do
-	case "$1" in
-		-h|--help)
+# Parse and apply flags.
+while getopts ":xh" option; do
+	case "$option" in
+		x)
+			set -x
+			;;
+		h)
 			help
 			exit
 			;;
-		--)
-			shift
-			break
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
 			;;
 	esac
 done
 
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-	echo "$0: missing argument, try --help for more information" >&2
-	exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
-target="$(scripts/parse "$1")"
-platform="$(scripts/inspect -P "$target")"
-name="$(scripts/inspect -n "$target")"
-archive="$(scripts/inspect -a "$target")"
+# Release tag, e.g. Add-on/42.
+tag="$1"
 
-mkdir -p dist
+# Add-on absolute path, e.g. /Add-on.
+target="$("$prefix/parse" -a "$tag")"
 
-git archive --format=zip -o "dist/$archive" --prefix="$name/" "$1:$platform/$name/"
+# Add-on name, e.g. Add-on.
+name="$("$prefix/inspect" -n "$target")"
 
+# Add-on archive, e.g. Add-on-v42.zip.
+archive="$("$prefix/inspect" -a "$target")"
+
+# Distributable directory, e.g. ./dist.
+dist="$target/dist"
+
+# Make sure distributable directory exists.
+mkdir -p "$dist"
+
+# Git root directory.
+root="$(git rev-parse --show-toplevel)"
+
+# Generate add-on archive.
+git archive --format=zip -o "$dist/$archive" --prefix="$name/" "$tag:${target#"$root"}"
diff --git a/scripts/env b/scripts/env
--- a/scripts/env
+++ b/scripts/env
@@ -1,13 +1,76 @@
 #!/usr/bin/env bash
 
+# Sane defaults.
 set -euo pipefail
 
-tag="${GITHUB_REF#refs/tags/}"
-target="${tag%/*}"
-release="$(scripts/inspect "$target")"
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
 
-cat <<-EOF > "$GITHUB_ENV"
-	TAG=$tag
-	TARGET=$target
-	RELEASE=$release
+# Print the manual.
+help() {
+	cat <<-EOF >&2
+		About
+		        Prepare envinroment variables from Git tag.
+
+		Usage
+		        $script -h
+		        $script [-x] <tag>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
+	EOF
+}
+
+# Parse and apply flags.
+while getopts ":xh" option; do
+	case "$option" in
+		x)
+			set -x
+			;;
+		h)
+			help
+			exit
+			;;
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
+			;;
+	esac
+done
+
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
+if test -z "$*"; then
+	echo "$script: missing required argument, see -h" >&2
+	exit
+fi
+
+# Test Git tag.
+if ! git rev-parse --verify --quiet "$1" >/dev/null 2>&1; then
+	echo "$script: invalid Git tag '$1'" >&2
+	exit
+fi
+
+# Unprefixed tag, e.g. Add-on/v42.
+tag="${1#refs/tags/}"
+
+# Add-on name, e.g. Add-on.
+target="${tag%/*}"
+
+# Release title, e.g. Add-on v42.
+release="$("$prefix/inspect" -r "$target")"
+
+# Output environment.
+cat <<-EOF
+	TAG="$tag"
+	TARGET="$target"
+	RELEASE="$release"
 EOF
diff --git a/scripts/inspect b/scripts/inspect
--- a/scripts/inspect
+++ b/scripts/inspect
@@ -1,9 +1,5 @@
 #!/usr/bin/env bash
 
-#
-# Inspect add-on information.
-#
-
 # Sane defaults.
 set -euo pipefail
 
@@ -18,12 +14,38 @@ script="$(basename "$script")"
 # Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $script [-xhVpmnivta] <path>
+		About
+		        Inspect add-on information.
+
+		Usage
+		        $script -h
+		        $script [-x] -V <path>
+		        $script [-x] -p <path>
+		        $script [-x] -m <path>
+		        $script [-x] -n <path>
+		        $script [-x] -i <path>
+		        $script [-x] -v <path>
+		        $script [-x] -t <path>
+		        $script [-x] -a <path>
+		        $script [-x] -r <path>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
+		        -V      Validate given path is a valid add-on.
+		        -p      Print add-on supported platforms.
+		        -m      Print add-on manifest file path.
+		        -n      Print add-on name.
+		        -i      Print add-on interface version.
+		        -v      Print add-on version.
+		        -t      Print add-on release tag.
+		        -a      Print add-on archive file name.
+		        -r      Print add-on release title.
 	EOF
 }
 
 # Parse and apply flags.
-while getopts ":xhVpmnivta" option; do
+while getopts ":xhVpmnivtar" option; do
 	case "$option" in
 		x)
 			set -x
@@ -56,6 +78,9 @@ while getopts ":xhVpmnivta" option; do
 		a)
 			output="archive"
 			;;
+		r)
+			output="release"
+			;;
 		?)
 			echo "$script: unknown flag '$OPTARG', try -h" >&2
 			exit
@@ -69,6 +94,12 @@ shift $((OPTIND - 1))
 # Test required arguments.
 if test -z "$*"; then
 	echo "$script: missing required argument, see -h" >&2
+	exit
+fi
+
+# Test required flags.
+if test -z "${output:-}"; then
+	echo "$script: missing required flag, see -h" >&2
 	exit
 fi
 
@@ -151,7 +182,7 @@ case "${output=}" in
 	archive)
 		echo "$name-v$version.zip"
 		;;
-	*)
+	release)
 		echo "$name v$version"
 		;;
 esac
diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -1,24 +1,70 @@
 #!/usr/bin/env bash
 
-#
-# Lint Lua and XML files recursively in a given directory.
-#
-
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
+help() {
+	cat <<-EOF >&2
+		About
+		        Lint Lua and XML files recursively in the given directory.
+
+		Usage
+		        $script -h
+		        $script [-x] <path>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
+	EOF
+}
+
+# Parse and apply flags.
+while getopts ":xh" option; do
+	case "$option" in
+		x)
+			set -x
+			;;
+		h)
+			help
+			exit
+			;;
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
+			;;
+	esac
+done
+
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-    echo "$0: missing argument. e.g. $0 <path>" >&2
-    exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
+# Target directory.
 target="$1"
 
+# Validate target directory.
 if ! test -d "$target"; then
-    echo "$target is not a directory." >&2
+    echo "$script: '$target' is not a directory" >&2
     exit 1
 fi
 
-platform="$(scripts/inspect --platform "$target")"
-
+# Lint Lua files.
 find "$target" -name "*.lua" -exec luacheck {} +
-find "$target" -name "*.xml" -exec xmllint --noout --schema "$platform/UI.xsd" {} +
+
+# Lint XML files.
+printf "\n"
+find "$target" -name "*.xml" -exec xmllint --noout --schema "$prefix/../UI.xsd" {} +
diff --git a/scripts/parse b/scripts/parse
--- a/scripts/parse
+++ b/scripts/parse
@@ -1,28 +1,88 @@
 #!/usr/bin/env bash
 
-#
-# Parse given Git tag into the respective add-on directory.
-#
-
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
+help() {
+	cat <<-EOF >&2
+		About
+		        Parse Git tag to get the respective add-on directory.
+
+		Usage
+		        $script -h
+		        $script [-xa] <tag>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
+		        -a      Print absolute path.
+	EOF
+}
+
+# Parse and apply flags.
+while getopts ":xha" option; do
+	case "$option" in
+		x)
+			set -x
+			;;
+		h)
+			help
+			exit
+			;;
+		a)
+			output="absolute"
+			;;
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
+			;;
+	esac
+done
+
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-    echo "$0: missing argument. e.g. $0 <tag>" >&2
-    exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
+# Release tag, e.g. Add-on/v42.
 tag="$1"
 
-if ! git rev-parse "$tag" >/dev/null 2>&1; then
-    echo "$0: '$tag' is not a valid tag" >&2
+# Output mode, e.g. absolute.
+output="${output:-relative}"
+
+# Tagged commit. e.g. 0123456789abcdef.
+commit="$(git rev-parse --verify --quiet "$tag" 2>/dev/null || :)"
+
+# Validate tag.
+if test -z "$commit"; then
+    echo "$script: '$tag' is not a valid tag" >&2
     exit 1
 fi
 
-target="${tag%/*}"
+# Manifest file path. e.g. Add-on/Add-on.toc.
+manifest="$(git diff-tree --no-commit-id --name-only -r "$commit")"
 
-if ! scripts/inspect "$target" >/dev/null; then
-    echo "$0: couldn't find corresponding add-on" >&2
-    exit 1
+# Print out relative path.
+if test "$output" = "relative"; then
+	dirname "$manifest"
+	exit 0
 fi
 
-realpath "$target" 
+# Git root directory.
+root="$(git rev-parse --show-toplevel)"
+
+# Print out absolute path.
+dirname "$root/$manifest"
diff --git a/scripts/upload b/scripts/upload
--- a/scripts/upload
+++ b/scripts/upload
@@ -1,64 +1,107 @@
 #!/usr/bin/env bash
 
-#
-# Upload archive to CurseForge.
-#
-
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $0 [-h]|-t <token> <tag>
+		About
+		        Upload distributable to CurseForge. Depends on jq.
+
+		Usage
+		        $script -h
+		        $script [-x] -t <token> <path>
+
+		Flags
+		        -h      Print this manual.
+		        -x      Enable debug mode.
+		        -t      CurseForge API token.
 	EOF
 }
 
-opts=$(getopt -n "$0" -o ht: -l help,token: -- "$@")
-
-if test $? -ne 0; then
-	exit 1
-fi
-
-eval set -- "$opts"
-
-while :; do
-	case "$1" in
-		-h|--help)
+# Parse and apply flags.
+while getopts ":xht:" option; do
+	case "$option" in
+		x)
+			set -x
+			;;
+		h)
 			help
 			exit
 			;;
-		-t|--token)
-			token="$2"
-			shift 2
+		t)
+			token="$OPTARG"
 			;;
-		--)
-			shift
-			break
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
 			;;
 	esac
 done
 
-tag="$1"
-target="$(scripts/parse "$tag")"
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
 
+# Test required arguments.
+if test -z "$*"; then
+	echo "$script: missing required argument, see -h" >&2
+	exit
+fi
+
+# Test required flags.
+if test -z "${token:-}"; then
+	echo "$script: missing required flag, see -h" >&2
+	exit
+fi
+
+# Test for jq.
+if ! command -v jq >/dev/null; then
+	echo "$script: missing dependency 'jq'" >&2
+	exit 1
+fi
+
+# Add-on directory path, e.g. ./Add-on.
+target="$1"
+
+# Validate target.
+"$prefix/inspect" -V "$target"
+
+# Check for .curseforge file.
 if ! test -f "$target/.curseforge"; then
-	echo "$0: '$target/.curseforge' is not a file" >&2
+	echo "$script: '$target/.curseforge' is not a file" >&2
 	exit 1
 fi
 
-archive="$(scripts/inspect -a "$target")"
+# Archive name, e.g. Add-on-v42.zip.
+archive="$("$prefix/inspect" -a "$target")"
 
-if ! test -f "dist/$archive"; then
-	echo "$0: dist/$archive is not a file" >&2
+# Distributable directory, e.g. ./dist.
+dist="$target/dist"
+
+# Test archive.
+if ! test -f "$dist/$archive"; then
+	echo "$script: '$dist/$archive' is not a file" >&2
 	exit 1
 fi
 
+# Read project id from .curseforge file.
 project_id="$(jq .projectId "$target/.curseforge")"
 
-# `$changelog` here is a jq variable.
-jq --rawfile changelog dist/CHANGELOG.md '.changelog = $changelog | del(.projectId)' .curseforge \
-	| jq -r tostring > metadata.json
+# Generate metadata. `$changelog` here is a jq variable.
+jq --rawfile changelog "$dist/CHANGELOG.md" '.changelog = $changelog | del(.projectId)' .curseforge \
+	| jq -r tostring > "$dist/metadata.json"
 
+# Upload to CurseForge.
 curl -vf -X POST "https://wow.curseforge.com/api/projects/$project_id/upload-file" \
 	-H "X-Api-Token: $token" \
-	-F "metadata=@metadata.json" \
-	-F "file=@dist/$archive"
+	-F "metadata=@$dist/metadata.json" \
+	-F "file=@$dist/$archive"
