wip: Refactor scripts

diff --git a/scripts/bump b/scripts/bump
--- a/scripts/bump
+++ b/scripts/bump
@@ -1,101 +1,70 @@
 #!/usr/bin/env bash
 
 #
-# Bump version of given add-on.
+# Bump version of the add-on.
 #
 
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $0 [-h|-p|-m|-M] <path>
+		Usage: $script [-xh] <path>
 	EOF
 }
 
-commits-since() {
-	local range
-	range="$(git describe --abbrev=0 --match "$1/*" 2>/dev/null | cut -f1 -d-)..HEAD"
-	git rev-list --count "${range#..}" -- "$1" 2>/dev/null
-}
-
-opts=$(getopt -n "$0" -o hpmM -l help,patch,minor,major -- "$@")
-
-if test $? -ne 0; then
-	exit 1
-fi
-
-eval set -- "$opts"
-
-while :; do
-	case "$1" in
-		-p|--patch)
-			bump="patch"
-			shift
+# Parse and apply flags.
+while getopts ":xh" option; do
+	case "$option" in
+		x)
+			set -x
 			;;
-		-m|--minor)
-			bump="minor"
-			shift
-			;;
-		-M|--major)
-			bump="major"
-			shift
-			;;
-		-h|--help)
+		h)
 			help
 			exit
 			;;
-		--)
-			shift
-			break
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
 			;;
 	esac
 done
 
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-	echo "$0: missing argument, try --help for more information" >&2
-	exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
+# Add-on directory path, e.g. ./Add-on.
 target="$1"
 
-if ! test -d "$target"; then
-	echo "$0: '$target' is not a directory" >&2
-	exit 1
-fi
+# Validate target.
+"$prefix/inspect" -V "$target"
 
-name="$(scripts/inspect -n "$target")"
-manifest="$target/$name.toc"
-platform="$(scripts/inspect -P "$target")"
+# Name of the add-on, e.g. Add-on.
+name="$("$prefix/inspect" -n "$target")"
 
-old_version="$(scripts/inspect -v "$target")"
+# Manifest file path. e.g. Add-on/Add-on.toc.
+manifest="$("$prefix/inspect" -m "$target")"
 
-patch="$(scripts/inspect -p "$target")"
-minor="$(scripts/inspect -m "$target")"
-major="$(scripts/inspect -M "$target")"
+# Version, e.g. 42.
+version="$("$prefix/inspect" -v "$target")"
 
-case "${bump=patch}" in
-	patch)
-		count=$(commits-since "$platform/$name")
-		patch=$((patch + count))
-		;;
-	minor)
-		patch=0
-		minor=$((minor + 1))
-		;;
-	major)
-		patch=0
-		minor=0
-		major=$((major + 1))
-		;;
-esac
+# Change version in the manifest.
+sed -i "s/Version: $version/Version: $((version + 1))/" "$manifest"
 
-new_version="$major.$minor.$patch"
-
-if test "$old_version" = "$new_version"; then
-	echo "$0: versions are identical" >&2
-	exit 1
-fi
-
-sed -i "s/Version: $old_version/Version: $new_version/" "$manifest"
-
-git commit -m "Bump $platform/$name to $new_version" "$manifest"
+# Commit the change.
+git commit -m "Bump $name to $((version + 1))" "$manifest"
diff --git a/scripts/inspect b/scripts/inspect
--- a/scripts/inspect
+++ b/scripts/inspect
@@ -1,125 +1,158 @@
 #!/usr/bin/env bash
 
 #
-# Inspect add-on information in given path.
+# Inspect add-on information.
 #
 
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $0 [-h|-P|-n|-v|-M|-m|-p|-t|-a] <path>
+		Usage: $script [-xhVpmnivta] <path>
 	EOF
 }
 
-opts=$(getopt -n "$0" -o hPnvMmpta -l help,platform,name,version,major,minor,patch,tag,archive -- "$@")
-
-if test $? -ne 0; then
-	exit 1
-fi
-
-eval set -- "$opts"
-
-while :; do
-	case "$1" in
-		-P|--platform)
-			output="platform"
-			shift
+# Parse and apply flags.
+while getopts ":xhVpmnivta" option; do
+	case "$option" in
+		x)
+			set -x
 			;;
-		-n|--name)
+		h)
+			help
+			exit
+			;;
+		V)
+			output="validate"
+			;;
+		p)
+			output="platforms"
+			;;
+		m)
+			output="manifest"
+			;;
+		n)
 			output="name"
-			shift
 			;;
-		-v|--version)
+		i)
+			output="interface"
+			;;
+		v)
 			output="version"
-			shift
 			;;
-		-M|--major)
-			output="major"
-			shift
-			;;
-		-m|--minor)
-			output="minor"
-			shift
-			;;
-		-p|--patch)
-			output="patch"
-			shift
-			;;
-		-t|--tag)
+		t)
 			output="tag"
-			shift
 			;;
-		-a|--archive)
+		a)
 			output="archive"
-			shift
 			;;
-		--)
-			shift
-			break
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
 			;;
 	esac
 done
 
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-	echo "$0: missing argument, try --help for more information" >&2
-	exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
+# Add-on directory path, e.g. ./Add-on.
 target="$1"
 
+# Test the add-on directory.
 if ! test -d "$target"; then
-	echo "$0: '$target' is not a directory" >&2
+	echo "$script: '$target' is not a directory" >&2
 	exit 1
 fi
 
+# Name of the add-on, e.g. Add-on.
 name="$(basename "$target")"
+
+# Manifest file path. e.g. Add-on/Add-on.toc.
 manifest="$target/$name.toc"
 
+# Test manifest file.
 if ! test -f "$manifest"; then
-	echo "$0: manifest could not be found" >&2
+	echo "$0: manifest '$manifest' is not a file" >&2
 	exit 1
 fi
 
+# Interface version, e.g. 11301.
 interface="$(grep -Po "Interface: \K.+" "$manifest")"
+
+# Add-on version, e.g. 42.
 version="$(grep -Po "Version: \K.+" "$manifest")"
 
+# Detect game from interface version.
 case "$interface" in
-	113*|205*|304*)
-		platform="classic"
+	3????)
+		platforms="Wrath"
+		;;
+	2????)
+		platforms="TBC"
+		;;
+	1????)
+		platforms="Vanilla"
+		;;
+	1?????|9????|8????)
+		platforms="Mainline"
 		;;
 	*)
-		platform="retail"
+		echo "$0: unrecognized interface version '$interface'" >&2
+		exit 1
 		;;
 esac
 
+# Detect additional supported platforms from suffixed manifest files.
+for f in "$target"/*_*.toc; do
+	f="${f#*_}"
+	platforms="$platforms,${f%%.*}"
+done
+
+# Output requested information.
 case "${output=}" in
-	platform)
-		echo "$platform"
+	validate)
+		exit 0
+		;;
+	platforms)
+		echo "$platforms"
+		;;
+	manifest)
+		echo "$manifest"
 		;;
 	name)
 		echo "$name"
 		;;
+	interface)
+		echo "$interface"
+		;;
 	version)
 		echo "$version"
 		;;
-	major)
-		echo "$version" | cut -f1 -d.
-		;;
-	minor)
-		echo "$version" | cut -f2 -d.
-		;;
-	patch)
-		echo "$version" | cut -f3 -d.
-		;;
 	tag)
-		echo "$platform/$name/$version"
+		echo "$name/v$version"
 		;;
 	archive)
-		echo "$name-$version-$platform.zip"
+		echo "$name-v$version.zip"
 		;;
 	*)
-		echo "$name $version ($platform)"
+		echo "$name v$version"
 		;;
 esac
 
diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,71 +1,71 @@
 #!/usr/bin/env bash
 
 #
-# Release new version of given add-on.
+# Release new version of the add-on.
 #
 
+# Sane defaults.
 set -euo pipefail
 
+# Find scripts directory.
+script="$0"
+if test -L "$script"; then
+	script="$(readlink -f "$0")"
+fi
+prefix="$(dirname "$script")"
+script="$(basename "$script")"
+
+# Print the manual.
 help() {
 	cat <<-EOF >&2
-		Usage: $0 [-h|-p|-m|-M] <path>
+		Usage: $script [-xh] <path>
 	EOF
 }
 
-opts=$(getopt -n "$0" -o hpmM -l help,patch,minor,major -- "$@")
-
-if test $? -ne 0; then
-	exit 1
-fi
-
-eval set -- "$opts"
-
-while :; do
-	case "$1" in
-		-p|--patch)
-			bump="patch"
-			shift
+# Parse and apply flags.
+while getopts ":xh" option; do
+	case "$option" in
+		x)
+			set -x
 			;;
-		-m|--minor)
-			bump="minor"
-			shift
-			;;
-		-M|--major)
-			bump="major"
-			shift
-			;;
-		-h|--help)
+		h)
 			help
 			exit
 			;;
-		--)
-			shift
-			break
+		?)
+			echo "$script: unknown flag '$OPTARG', try -h" >&2
+			exit
 			;;
 	esac
 done
 
+# Drop flags by shifting arguments.
+shift $((OPTIND - 1))
+
+# Test required arguments.
 if test -z "$*"; then
-	echo "$0: missing argument, try --help for more information" >&2
-	exit 1
+	echo "$script: missing required argument, see -h" >&2
+	exit
 fi
 
+# Add-on directory path, e.g. ./Add-on.
 target="$1"
 
-if ! test -d "$target"; then
-	echo "$0: '$target' is not a directory" >&2
-	exit 1
-fi
+# Validate target.
+"$prefix/inspect -V" "$target"
 
-if ! scripts/lint "$target"; then
-	echo "$0: linting failed" >&2
-	exit 1
-fi
+# Lint add-on source.
+"$prefix/lint" "$target"
 
-scripts/bump "--${bump=patch}" "$target"
+# Bump the add-on's version.
+"$prefix/bump" "$target"
 
-release="$(scripts/inspect "$target")"
-tag="$(scripts/inspect -t "$target")"
+# Release's title, e.g. Add-on v42.
+release="$("$prefix/inspect" "$target")"
 
+# Tag, e.g. Add-on/v42.
+tag="$("$prefix/inspect" -t "$target")"
+
+# Tag and push.
 git tag -m "Release $release" "$tag"
 git push --follow-tags
