Update release and locate scripts

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -8,15 +8,17 @@ help() {
 	EOF
 }
 
-last-tag() {
-	git rev-list --tags --no-walk -n 1 -- "$1" 2>/dev/null
+last-tagged-commit() {
+	git rev-list --tags --no-walk -- "$1" | head -1 2>/dev/null
 }
 
-commits-since-last-tag() {
-	git log --oneline "$(last-tag "$1")..HEAD" -- "$1" 2>/dev/null
+commits-since-last-tagged-commit() {
+	git rev-list "$(last-tagged-commit "$1")..HEAD" -- "$1" 2>/dev/null
 }
 
-bump
+changelog() {
+	git log --oneline "$(last-tagged-commit "$1")..HEAD" -- "$1" | grep "#[0-9]+" 2>/dev/null
+}
 
 options=$(getopt -n "$0" -o hpmM -l help,patch,minor,major -- "$@")
 
@@ -24,7 +26,7 @@ if test $? -ne 0; then
 	exit 1
 fi
 
-set -- $options
+eval set -- "$options"
 
 while :; do
 	case "$1" in
@@ -78,13 +80,13 @@ patch="$(echo "$old_version" | cut -f3 -d.)"
 
 case "${mode=patch}" in
 	patch)
-		patch=$(commits-since-last-tag "$platform/$name" | wc -l)
+		patch=$(commits-since-last-tagged-commit "$platform/$name" | wc -l)
 		;;
 	minor)
 		patch=0
 		minor=$((minor + 1))
 		;;
-	minor)
+	major)
 		patch=0
 		minor=0
 		major=$((major + 1))
@@ -93,10 +95,19 @@ esac
 
 new_version="$major.$minor.$patch"
 
+if test "$old_version" = "$new_version"; then
+	echo "$0: aborting, versions are identical" >&2
+	exit 1
+fi
+
 sed -i "s/Version: $old_version/Version: $new_version/" "$manifest"
 
 git commit -m "Bump $platform/$name to $new_version" "$manifest"
 
-git tag "$platform/$name/$new_version"
+cat <<-EOF | git tag -F - "$platform/$name/$new_version"
+	$name $new_version ($platform)
+
+	$(changelog "$(dirname "$manifest")")
+EOF
 
 git push --follow-tags
