Update release script

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -12,16 +12,15 @@ if ! test -d "$1"; then
     exit 1
 fi
 
-if ! git diff --quiet; then
-    echo "The working tree is dirty, please clean up" >&2
-    # exit 1
-fi
+# if ! git diff --quiet; then
+#     echo "The working tree is dirty, please clean up" >&2
+#     exit 1
+# fi
 
-mode="$(dirname \"$1\")"
-name="$(basename \"$1\")"
-version="$(grep -Po "Version: \K.+" \"$1/$name.toc\")"
-tag="$(echo \"$mode/$name/$version\" | tr '[:upper:]' '[:lower:]')"
+mode="$(dirname "$1")"
+name="$(basename "$1")"
+version="$(grep -Po "Version: \K.+" "$1/$name.toc")"
+tag="$(echo "$mode/$name/$version" | tr "[:upper:]" "[:lower:]")"
 
 git tag "$tag"
-git push --tags
 git archive --format=zip -o "$mode/$name-$version.zip" --prefix="$1" HEAD .
