Split release script into release (tag) and archive

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -1,26 +1,24 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 set -eu
 
-if test "$1" = ""; then
-    echo "Missing argument, e.g. retail/Fastbind" >&2
+if test -z "$1"; then
+    echo "Missing argument, e.g. $0 classic/Fastbind" >&2
     exit 1
 fi
 
 if ! test -d "$1"; then
-    echo "$1 does not exist" >&2
+    echo "$1 is not a directory" >&2
     exit 1
 fi
 
-# if ! git diff --quiet; then
-#     echo "The working tree is dirty, please clean up" >&2
-#     exit 1
-# fi
-
-mode="$(dirname "$1")"
+platform="$(dirname "$1")"
 name="$(basename "$1")"
 version="$(grep -Po "Version: \K.+" "$1/$name.toc")"
-tag="$(echo "$mode/$name/$version" | tr "[:upper:]" "[:lower:]")"
+tag="$1/$version"
 
-git tag "$tag" > /dev/null 2>&1 || echo "Already tagged."
-git archive --format=zip -o "$mode/$name-$version.zip" --prefix="$1" HEAD .
+if git tag "$tag" > /dev/null 2>&1; then
+    git push --tags
+else
+    echo "Tag $tag already exists." >&2
+fi
